#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

 ::neden::neden 🤔
 ::kızlar::kızlar 👧
 ::kız::kız 👧
 ::beğen::beğen 😄
 ::sebze::sebze 🍆
 ::sebzeler::sebzeler 🍆🍆
 ::ben::ben 👈
 ::yürümek::yürümek 🚶
 ::yürüyüş::yürüyüş 🚶
 ::beğen::beğen 👍
 ::begeniler::begeniler 👍
 ::beğendim::beğendim 😍
 ::aşk::aşk ❤
 ::aşklar::aşklar ♥
 ::sevilen::sevilen 💖
 ::bir::bir 👆
 ::kalça::kalça 🍑
 ::göt::göt 🍑
 ::kalçalar::kalçalar 🍑
 ::bahçe::bahçe 🌺🌻🌸
 ::yıl::yıl 📅
 ::tarih::tarih 👫
 ::kız::kız 👩
 ::dedi::dedi 💬
 ::dedin::dedin 💬
 ::söyledin::söyledin 💬
 ::söyleyerek::söyleyerek 💬
 ::durdur::durdur 🛑
 ::durur::durur 🛑
 ::durdu::durdu 🛑
 ::olmaz::olmaz 🚫👇
 ::düşünmek::düşünmek 🤔💭
 ::düşün::düşün 🤔💭
 ::düşünür::düşünür 🤔💭
 ::dostum::dostum 😎
 ::nezaman ::ne zaman ⏰
 ::sol::sol 👈
 ::hiç::hiç ❌
 ::bitti::bitti 😳
 ::sağ::sağ 👉
 ::al::al 👊
 ::kasık::kasık 🍑
 ::popo::popo 🍑
 ::zaman::zaman 🕐
 ::postladı::postladı 📲
 ::post::post 📲
 ::instagram::instagram 📸💯
 ::insta::insta 📸💯
 ::şanslı::şanslı 🍀
 ::çocuklar::çocuklar 👨🏾
 ::çocuklar::çocuklar 👨🏾
 ::fındık::fındık 🥜
 ::31::31 💦
 ::resim::resim 📸
 ::resimler::resimler 📸
 ::yaşlı::yaşlı 👴
 ::erkek::erkek 👦
 ::ağalar::ağalar 🗿🗿
 ::hikaye::hikaye 📖
 ::orgazm::orgazm 💦
 ::atladı::atladı ⬆
 ::zıpla::zıpla ⬆
 ::acı::acı 📐
 ::beden::beden 💃
 ::iki::iki ✌
 ::hafta::hafta 📅
 ::gün::gün 📅
 ::dudak::dudak 👄
 ::dudaklar::dudaklar 👄
 ::mutfak::mutfak 🍴
 ::mutfağa::mutfağa 🍴
 ::hoca::hoca 👩‍🏫
 ::öğretim::öğretim 👩‍🏫
 ::bak::bak 👀
 ::gördüm::gördüm 👀
 ::sınıf::sınıf 🏫
 ::okul::okul 🏫
 ::sandalye::sandalye 💺
 ::zoom::zoom ⚡
 ::koştu::koştu 🏃
 ::kaç::kaç 🏃
 ::koşu::koşu 🏃
 ::boşaldı::boşaldı 💦
 ::tanrı::tanrı 😇✝
 ::ne::ne 🙀
 ::aradı::aradı 📞
 ::ara::ara 📞
 ::tokat::tokat 👋🏾
 ::oynadı::oynadı 🎮
 ::oyun::oyun 🎮
 ::oynar::oynar 🎮
 ::koşş::koşş 🏃🏿‍♂️
 ::hindi::hindi 🦃
 ::büyük::büyük 😱
 ::çığlık::çığlık 😱
 ::geri::geri 🔙
 ::yüz::yüz 😀
 ::ateşle::ateşle 💦
 ::aşağı::aşağı 👇
 ::yukarı::yukarı ☝
 ::bye::bye 👋
 ::ac::ac 🔛
 ::posta::posta 💦
 ::kaydedildi::kaydedildi 💾
 ::kaydet::kaydet 💾
 ::robot::robot 🤖
 ::kelimeler::kelimeler 🔚
 ::hayal::hayal 🤔
 ::engelli::engelli ♿
 ::makarnalar::makarnalar 😩
 ::makarna::makarna 😩
 ::foto::foto 👌👀
 ::külot::külot 👙
 ::olmadan::olmadan ❌
 ::normal::normal 😐
 ::kedi::kedi 🐱
 ::yaymak::yaymak 👐
 ::bit::bit 😁
 ::gönder::gönder 📩
 ::seksi::seksi 🍆💦
 ::sex::sex 💦
 ::sizin::sizin 👉👈
 ::parmaklar::parmaklar 🖐
 ::yo::yo 👋
 ::dur::dur ✋
 ::lav::lav 🌋
 ::yarrak::yarrak 🍆
 ::minik::minik 👌🏼
 ::asla::asla 🙅
 ::cılız::cılız 😎
 ::görmezden::görmezden 😷
 ::komik::komik 😆
 ::komik::komik 😄
 ::ateist::ateist ⛪❌
 ::videoyunlari::videoyunlari 🎮
 ::videoyun::videoyun 🎮
 ::anladım::anladım ✍
 ::kitaplar::kitaplar 📚
 ::yanlış::yanlış 😱❌
 ::arama::arama 🕵
 ::oyun::oyun 🎮
 ::kanıt::kanıt 📊
 ::mantık::mantık 👌
 ::tümü::tümü 🙆
 ::yapma::yapma ❌
 ::bakım::bakım 💅
 ::Garfield::Garfield 🐱
 ::zaman::zaman ⏳
 ::ters::ters 🙃
 ::spagetti::spagetti 👌
 ::yandı::yandı 🔥
 ::trump::trump 🍊
 ::porno::porno 🌽
 ::uçak::uçak ✈
 ::uçaklar::uçaklar ✈
 ::çizgi::çizgi 〰
 ::check::check ✅
 ::toplar::toplar 🏀
 ::top::top 🏀
 ::show::show 📺
 ::güvenlik::güvenlik 🚔
 ::açıkça::açıkça 🙄
 ::kaldırıldı::kaldırıldı 🚫
 ::sil::sil 🚫
 ::oku::oku 📖
 ::kelime::kelime 📝
 ::lütfen::lütfen 🙏
 ::pls::pls 🙏
 ::kapalı::kapalı 📴
 ::sonbahar::sonbahar 🍁
 ::git::git ☝️🏃
 ::kamp::kamp ⛺
 ::bilim::bilim 🔬
 ::best::best 🏆💯
 ::ağla::ağla 😭
 ::duygular::duygular 😜
 ::yalan::yalan 🤥
 ::metin::metin 📝
 ::bot::bot 🤖
 ::script::script 🤖
 ::obez::obez 🐋
 ::bok::bok 💩
 ::tuvalet::tuvalet 🚽
 ::telefon::telefon 📱
 ::nedenler::nedenler 🌟
 ::destek::destek ❤
 ::Obama::Obama 👦🏾
 ::konuşma::konuşma 🗣
 ::harita::harita 🗾
 ::uygunsuz::uygunsuz 🔞
 ::açıklamak::açıklamak 📢
 ::parça::parça 🍗
 ::sert::sert 💪
 ::nah::nah 🖕
 ::emin::emin 💯
 ::gerçek::gerçek 💯
 ::xbox::xbox ❌
 ::gelişmiş::gelişmiş 💯
 ::emojifier::emojifier 😂
 ::mutlu::mutlu 😂
 ::eğlence::eğlence 🤗
 ::bağlantı::bağlantı 📎
 ::yorum::yorum 📝
 ::yorumlar::yorumlar 📝
 ::kaynak::kaynak 🍆💦
 ::kusmak::kusmak 🤮
 ::upload::upload 📂
 ::film::film 🎞️
 ::sinema::sinema 🎞️
 ::filmler::filmler 🎞️
 ::dosya::dosya 📂
 ::dosyalar::dosyalar 📂
 ::sabitle::sabitle 📌
 ::düz::düz 📏
 ::gay::gay 🌈
 ::mum::mum 🕯️
 ::zenci::zenci ❌
 ::nigger::nibber 😱
 ::ibne::ibne 🚬
 ::uyku::uyku 🛌💤
 ::uyuyor::uyuyor 💤
 ::sıkıcı::sıkıcı 💤
 ::anlamadım::anlamadım 🤨
 ::anlamıyorsun::anlamıyorsun ❌
 ::birthday::birthday 🥳
 ::parti::parti 🎉
 ::çift::çift 💑
 ::tavşan::tavşan 😍🐰
 ::ateş::ateş 🔥
 ::harika::harika 😎
 ::beans::beans 🚗✌️
 ::kolej::kolej 🎓
 ::öğrenci::öğrenci 🎓
 ::çalış::çalış 📜
 ::epic::epic 💯
 ::meme::meme 😂
 ::cum::cum 💦
 ::cumming::cumming 💦
 ::cummybot::CummyBot 🍆🍑
 ::yavaş::yavaş 🐌
 ::sayfa::sayfa 📄
 ::hey::hey 👋
 ::af::af 😤
 ::kötü::kötü 👎
 ::iyi::iyi 👌
 ::izle::izle 👀
 ::izledim::izledim 👀
 ::anime::anime 🎞️🗾
 ::pedo::pedo 🐻
 ::underage::underage 🔞
 ::konuşurken::konuşurken 👄
 ::sohbet::sohbet 💬
 ::insan::insan 🧑
 ::varlık::varlık 👾
 ::değer::değer 📈
 ::değerler::değerler 📈
 ::reddit::reddit 🤢
 ::redditor::redditor 👺
 ::yapamaz::yapamaz 🚫
 ::imkansız::imkansız 😱
 ::alay::alay 🙃
 ::alaycı::alaycı 💁‍♂️
 ::uzay::uzay 🌌
 ::copypasta::copypasta 😩👌
 ::copypastas::copypastas 
 ::kullanılabilir::kullanılabilir 😬
 ::harika::harika 🔥🔥
 ::saat::saat 🕔
 ::kalp::kalp ❤️
 ::silah::silah 🔫
 ::hata::hata 😱
 ::ol::ol 💀
 ::operasyon::operasyon 🔪
 ::hayat::hayat ⛑
 ::harika::harika 🎇
 ::sahte::sahte 🚨
 ::haberler::haberler 🚨
 ::pikachu::pikachu ⚡️
 ::emojify::emojify 😀
 ::kaybol::kaybol ❗️
 ::aile::aile 👨‍👩‍👧‍👦
 ::umut::umut 🤞
 ::sil::sil ❎
 ::silindi::silindi 🔪❎
 ::spez::spez 👎
 ::demek::demek 🤔
 ::yaratan::yaratan 😇
 ::emoji::emoji 😔
 ::aldatmak::aldatmak 😨
 ::aldat::aldat 💔😢
 ::cummy::cummy 💖
 ::onlar::onlar 👯
 ::kaçırdı::kaçırdı 🔫
 ::tutku::tutku 😳
 ::kısa::kısa 🤏
 ::yazmak::yazmak 📜✏️
 ::yazma::yazma ✏️
 ::deneme::deneme 📜
 ::nta::nta 🤗🤗
 ::yta::yta 😡😡
 ::kızgın::kızgın 😡
 ::öldu::öldu 💀
 ::ve::ve 👏
 ::benim::😜
 ::hapis::hapis 🚔
 ::sana::sana 👆
 ::sadece::sadece ❎
 ::tut::tut ✊
 ::çete::çete 🗿
 ::garip::garip 😳
 ::sevmemek::sevmemek 👎
 ::beğenmedim::beğenmedim 👎
 ::anket::anket 📊
 ::şimdi::şimdi 👉🕑
 ::ayıp::ayıp 👉👈
 ::nsfw::nsfw 🔞💦
 ::mesajlar::mesajlar 📬
 ::vur::vur ✊
 ::on::on 🚪
 ::o::o 👈
 ::parlaklık::parlaklık 🎇
 ::mutlak::mutlak 💯
 ::kesinlikle::kesinlikle 💯
 ::upvote::upvote ⬆️
 ::upvoted::upvoted ⬆️
 ::downvote::downvote ⬇️
 ::downvoted::downvoted ⬇️
 ::oy::oy 🗳️
 ::oyladı::oyladı 🗳️
 ::oylamak::oylamak 🗳️
 ::nazik::nazik 😊
 ::nazikçe::nazikçe 😊
 ::şarkı::şarkı 🎤😀
 ::şöyle::şöyle 🎤
 ::çiçek::çiçek 🌼
 ::çiçekler::flowers 🌼🌺🌼
 ::kuş::kuş 🐦
 ::kuşlar::kuşlar 🐦
 ::saniye::saniye ⏱️
 ::tavsancik::tavsancik 🐇
 ::coom::coom 😤
 ::kan::kan 🩸
 ::kanama::kanama 🩸
 ::kanamadan::kanamadan 🩸
 ::bağış::bağış 💰
 ::oha::oha 😮
 ::ödül::ödül 🏆
 ::ödüller::ödüller 🏆
 ::safsata::safsata 😳
 ::konu::konu 🤭
 ::küçük::küçük 🤏
 ::azgın::azgın 😉
 ::pahalı::pahalı 💰
 ::karen::karen 👱🏼‍♀️
 ::popüler::popüler 😎
 ::süt::süt 🥛
 ::boyut::boyut 😱
 ::çok::çok 🔥
 ::farklı::farklı 😡
 ::ugh::ugh 😩
 ::bak::bak 👀
 ::et::et 🥓
 ::döv::döv ✊
 ::tavuk::tavuk 🐓
 ::nugget::nugget 🍗
 ::çuval::çuval 💰
 ::break::break 💔
 ::tutuş::tutuş 💪
 ::büyü::büyü ✨
 ::ben::ben 🧑
 ::aşık::aşık 😍
 ::köpek::köpek 🐕
 ::köpekler::köpekler 🐕
 ::kedi::kedi 🐱
 ::kediler::kediler 🐱
 ::fil::fil 🐘
 ::öşür::öşür 😮💨
 ::osuruk::osuruk 😮💨
 ::kurt::kurt 🐺
 ::tilki::tilki 🦊
 ::aslan::aslan 🦁
 ::kaplan::kaplan 🐯
 ::at::at 🐎
 ::atlar::atlar 🐎
 ::domuz::domuz 🐖
 ::domuzcuk::domuzcuk 🐖
 ::domuzlar::domuzlar 🐖
 ::keçi::keçi 🐐
 ::fare::fare 🐭
 ::sıçan::sıçan 🐀
 ::ayı::ayı 🐻
 ::yılan::yılan 🐍
 ::piton::piton 🐍
 ::kurbağa::kurbağa 🐸
 ::balık::balık 🐟
 ::arı::arı 🐝
 ::ay::ay 🌕
 ::güneş::güneş 🌞
 ::yağmur::yağmur ☔
 ::yağmurlu::yağmurlu ☔
 ::ışık::ışık ⚡
 ::kartanesi ::kar tanesi ❄️
 ::kartaneleri ::kar taneleri ❄️
 ::liberal::liberal 😒
 ::liberaller::liberaller 😒
 ::üniversite::üniversite 🏫🎓
 ::çiftçi::çiftçi 🌽
 ::çiftçiler::çiftçiler 🌽
 ::fikir::fikir 💡
 ::fikirler::fikirler 💡
 ::not::not 📓
 ::hece::hece 🐝
 ::hecelemek::hecelemek 🐝
 ::orjinal::original 🌿
 ::gülüyor::gülüyor 😂
 ::gülmek::gülmek 😂
 ::güldü::güldü 😂
 ::neşe::neşe 😂
 ::löl::löl 😂👌
 ::değil::değil ❌
 ::bazinga::bazinga 🤣
 ::muhabir::muhabir 🎤
 ::bağır::bağır 🗣️
 ::bağırmak::bağırmak 🗣️
 ::şans::şans 🍀
 ::dayanmak::dayanmak 👀
 ::cuk::cuk 👀👄
 ::hesap::hesap 💳
 ::iz::iz 🔬
 ::bitirmek::bitirmek 👅
 ::bitirme::bitirme 👅
 ::bitmiş::bitmiş 👅
 ::terim::terim 📄
 ::inanılmaz::inanılmaz 💩
 ::joe::joe 😳
 ::sor::sor 🙏
 ::bana::bana 👦👈
 ::kadar::kadar 🤏
 ::seni::seni 👉
 ::kapat::kapat 🚫
 ::bütün::bütün 🙆‍♂️
 ::uykulu::uykulu 💤
 ::gidiyor::gidiyor 🏃
 ::zehir::zehir 🐍💀
 ::sessizlik::sessizlik 🤫
 ::sessiz::sessiz 🤫
 ::kral::kral 👑
 ::ördek::ördek 🦆
 ::endişe::endişe 😟
 ::endişeli::endişeli 😟
 ::endişelenmek::endişelenmek 😟
 ::ödünç::ödünç 🤲
 ::tutmak::tutmak 🤲
 ::lider::lider 🥇
 ::donald::donald 🦆
 ::putin::putin 🎖️
 ::anlaşma::anlaşma 🤝
 ::dağıtma::dağıtma 💰
 ::vahşi::vahşi 🤪
 ::çılgın::çılgın 🤪
 ::uwu::uwu 🐱🐵🦊
 ::owo::owo 🦊🐱🐱
 ::bayrak::bayrak 🏳️
 ::bayraklı::bayraklı 🏳️
 ::kırmızı::kırmızı 🚩
 ::beyaz::beyaz 👨🏻
 ::mavi::mavi 📘
 ::siyah::siyah 👨🏿
 ::yeşil::yeşil 🍏
 ::cinayet::cinayet 🔪💀
 ::öldürüldü::öldürüldü 🔪💀
 ::bıçak::bıçak 🔪
 ::bıçaklar::bıçaklar 🔪🔪🔪
 ::genç::genç 👶
 ::bebe::bebe 👶
 ::yaşlı::yaşlı 👴
 ::aptal::aptal 🤤
 ::mal::mal 🤕
 ::sıkış::sıkış 🍆
 ::becerdin::becerdin 🍆😩
 ::şıktır::şıktır 🍆😩
 ::gerizekali::gerizekali 👺
 ::salak::salak 👺
 ::yüksek::yüksek 👠
 ::uzun::uzun 📏
 ::uzuun::uzuun 📏
 ::uzuuun::uzuuun 📏
 ::gönderildi::gönderildi 📩
 ::şaka::şaka 🃏
 ::joker::joker 🤡
 ::şaka::şaka 🃏
 ::karpuz::karpuz 🍉
 ::elma::elma 🍎
 ::ekmek::ekmek 🍞
 ::peynir::peynir 🧀
 ::pizza::pizza 🍕
 ::yumurta::yumurta 🥚
 ::tuzlu::tuzlu 🧂
 ::kek::kek 🍰
 ::cakeday::cakeday 🍰
 ::buz::buz 🧊
 ::tren::tren 🚆
 ::kamyon::kamyon 🚚
 ::uçmak::uçmak ✈️
 ::flying::flying ✈️
 ::uçak::uçak ✈️
 ::canlı::canlı ⏳
 ::günler::günler 📅
 ::kârı::kârı 👩
 ::koca::koca 👨
 ::çocuk::çocuk 👶
 ::çocuklar::çocuklar 👶
 ::oğlu::oğlu🧒
 ::çocuklar::çocuklar 🧒
 ::gizli::gizli 🔎
 ::gizle::gizle 🔎
 ::vazgeç::vazgeç 😢
 ::yetenek::yetenek 🤙
 ::kürtaj::kürtaj 😤
 ::yukarıda::yukarıda 🡱
 ::istismar::istismar 🤕
 ::kabuletmek ::kabul etmek 🤝
 ::hakkında::hakkında 🙄
 ::gel::gel 😳
 ::yap::yap 🙆
 ::bul::bul 🧐
 ::al::al 😳
 ::vermek::vermek 🤲
 ::burada::burada 🤚
 ::biliyorum::biliyorum 😏
 ::oluştur::oluştur 🤑
 ::made::made 🤑
 ::erkek::erkek 🧑
 ::saniye::ikinci 🥈
 ::üçüncü::üçüncü 🥉
 ::çokça::çokça 👅
 ::fazlasıyla::fazlasıyla 😨
 ::yeni::yeni 🣡
 ::hayır::hayır 🚫
 ::insanlar::insanlar 👬
 ::almak::almak 👊
 ::şöyle::şöyle 🗣
 ::bu::bu 👏
 ::sen::sen 👆
 ::hanımefendi::hanımefendi 😍😍
 ::neymiş::neymiş ✋
 ::neyse::neyse 🌝
 ::piç::piç 🤬
 ::kaşar::kaşar 🧀
 ::ha?::ha? 🙄
 ::tehdit::tehdit 🤨
 ::amına koyim::amına koyim 😏
 ::evladı::evladı 👱‍
 ::am::am 😌
 ::amcı::amcı 😠
 ::amguard::amguard 🛡👩‍
 ::sus::sus 🤐
 ::türk::türk 🇹🇷
 ::türkçe::türkçe 🇹🇷
 ::cCc::cCc 🇹🇷
 ::abo::abo 🆎🅾
 ::abi::abi 👊
 ::galiba::galiba 🤔
 ::yaa::yaa 😔
 ::bilmem::bilmem 🤷‍
 ::mealini::mealini 📖
 ::başarılı::başarılı ✔
 ::gereksiz::gereksiz 🗑
 ::çöp::çöp 🗑
 ::yapım::yapım 🚧
 ::aşaması::aşaması 📉
 ::aşamasında::aşamasında 📉
 ::stonks::stonks 📈
 ::not stonks::not stonks 📉
 ::soru::soru ❓
 ::buldum::buldum 🔍
 ::ekliyor::ekliyor ➕
 ::ekle::ekle ➕
 ::ekledi::ekledi ➕
 ::tam::tam 👌
 ::yemek::yemek 🍲
 ::hı hım::hı hım ✅
 ::evet::evet ☑
 ::ama::ama 🤚
 ::sence::sence 👆🤔
 ::ekleyebilirim::ekleyebilirim ➕
 ::lan?::lan? 🤨
 ::lan::lan 😡
 ::botu::botu 🤖
 ::böyle::böyle 🤔
 ::geldim::geldim 💦
 ::nasılsınız::nasılsınız 🤗
 ::adam::adam 🤵
 ::söz::söz 🙏
 ::hmm::hmm 🤔
 ::votka::votka 🍾
 ::beyler::beyler 👨‍
 ::global::global 🌍
 ::nasıl::nasıl 🤔
 ::arkadaşlar::arkadaşlar 🤗
 ::güzel::güzel 🥰
 ::sonra::sonra ⌛
 ::en::en 😮
 ::mu::mu ❓
 ::biraz::biraz 🤏
 ::ulan::ulan 😠
 ::üzüldüm::üzüldüm 😥
 ::üzgün::üzgün 😥
 ::üzgünüm::üzgünüm 😥
 ::üzdün::üzdün 😥
 ::sewgi::sewgi ❤️
 ::kawga::kawga 👊
 ::doğru::doğru ✅
 ::selam::selam 👋
 ::selamlar::selamlar 👋
 ::merhaba::merhaba 👋
 ::yaşasın::yaşasın ırkımız çin'e bedel kırkımız söylenir türkümüz çağlardan çağlara turan'dır yurdumuz genç atsızlar ordumuz ulusun kurdumuz dağlardan dağlara
 ::mi::mi ❓
 ::nasılsın::nasılsın 🤗
 ::şey::şey 👉👈
 ::yok::yok ❌
 ::oynuyorduk::oynuyorduk 🎮
 ::program::program 👨‍💻
 ::programla::programla 👨‍💻
 ::yazılım::yazılım 👨‍💻
 ::ee::ee 🤔
 ::yayın::yayın 💻
 ::yayını::yayını 💻
 ::yayınını::yayınını 💻
 ::aa::aa 😯
 ::bende::bende ☺
 ::teşekkür ederim::teşekkür ederim 🙏
 ::test::test 📄
 ::doğruyu::doğruyu ✅
 ::söyle::söyle 🗣
 ::havalı::havalı 😎
 ::hawli::hawli 😎
 ::teşekkürler::teşekkürler 🙏
 ::heh::heh 
 ::eyvah::eyvah 😱
 ::dostum::dostum 🥰
 ::kimse::kimse 🙅‍♂️
 ::senin::senin ☝
 ::fikrin::fikrin 💭
 ::fikir::fikir 💭
 ::fikrini::fikrini 💭
 ::değiştiremez::değiştiremez ❌
 ::noldu::noldu 🤔
 ::üzücü::üzücü 😔
 ::düşünceli::düşünceli 😔
 ::aşkım::aşkım ❤
 ::problem::problem 📚
 ::mükemmel::mükemmel 🔥
 ::terliyorum::terliyorum 🥵
 ::terlemek::terlemek 🥵
 ::terledim::terledim 🥵
 ::sıcak::sıcak 🥵
 ::tamam::tamam ☑
 ::oldu::oldu 😶
 ::onu::onu 😶
 ::bunu::bunu 👈
 ::gibi::gibi 🤔
 ::arıyorum::arıyorum 🔎
 ::iğrenç::iğrenç 🤮
 ::ekliyorum::ekliyorum ➕
 ::kuscam::kuscam 🤮
 ::nereye::nereye 🤔👣
 ::pepega::pepega 🤪
 ::sinirlendim::sinirlendim 😡
 ::yanarız::yanarız 🔥
 ::silivri::silivri 🚓👮‍♂️
 ::soğuktur::soğuktur ❄🥶
 ::soğuk::soğuk 🥶
 ::terbiyesiz::terbiyesiz 🙅‍♂️⛔
 ::terbiyesizlik::terbiyesizlik 🙅‍♂️⛔
 ::bakma::bakma 👀❎
 ::bugün::bugün 📆👈
 ::yarın::yarın 📆👈
 ::malsın::malsın 🤪
 ::bass::bass 💪
 ::uyarmak::uyarmak ⚠
 ::uyarı::uyarı ⚠
 ::uyarıyorum::uyarıyorum ⚠
 ::uyarmam::uyarmam ⚠
 ::dalga::dalga 🌊
 ::dalgana::dalgana 🌊
 ::dalgaya::dalgaya 🌊
 ::dalganı::dalganı 🌊
 ::mı::mı ❔
 ::için::için 🧩
 ::aşırı::aşırı 🔥
 ::rahatlatıcı::rahatlatıcı 😌
 ::rahat::rahat 😌
 ::rahatladım::rahatladım 😌
 ::sakin::sakin 😶
 ::bağışla::bağışla 🙏😟
 ::beni::beni 👈
 ::programı::programı 👨‍💻
 ::ab::ab 🆎
 ::kitaplık::kitaplık 📚
 ::kitaplığım::kitaplığım 📚
 ::kitaplığa::kitaplığa 📚
 ::afrodizyak::afrodizyak 🧪🤭
 ::korku::korku 😱
 ::yalarım::yalarım 👅
 ::pasta::pasta 🍰
 ::geliştirmek::geliştirmek 📈
 ::geliştirirken::geliştirirken 📈
 ::oyunu::oyunu 🎮
 ::müdür::müdür 🎩
 ::beyefendi::beyefendi 🎩🧐
 ::çıkarma::çıkarma ➖
 ::çıkarıyor::çıkarıyor ➖
 ::yayınındayım::yayınındayım 💻
 ::goril::goril 🦍
 ::uga::uga 🦍
 ::buga::buga 🦍
 ::kardeşim::kardeşim 👊
 ::krşm::krşm 👊
 ::fikirlerinizi::fikirlerinizi 💭
 ::bekliyorum::bekliyorum 💤
 ::günaydın::günaydın 🌞😊
 ::herkese::herkese 🙆‍♂️
 ::herkes::herkes 🙆‍♂️
 ::tepki::tepki 😡
 ::doğmuştur::doğmuştur 👶
 ::doğmuş::doğmuş 👶
 ::doğa::doğa 🌳
 ::hangi::hangi 🤔
 ::cisim::cisim 🏐
 ::oynuyorum::oynuyorum 🎮
 ::knk::knk 👊
 ::boşver::boşver 🤷‍♂️
 ::ulaşma::ulaşma 🚗
 ::ulaşmanı::ulaşmanı 🚗
 ::ulaşım::ulaşım 🚗
 ::illet::illet 🤮
 ::illetten::illetten 🤮
 ::illeti::illeti 🤮
 ::kurtul::kurtul 👼
 ::kurtuldum::kurtuldum 👼
 ::patlar::patlar 💥
 ::boom::boom 💥
 ::bum::bum 💥
 ::patladı::patladı 💥
 ::patlıyor::patlıyor 💥
 ::patlamadı::patlamadı 💥❌
 ::bence::bence 👈🤔
 ::izleme::izleme 👀
 ::abla::abla 👊
 ::devam::devam 🛫
 ::hasta::hasta 🤒
 ::musun::musun ❓
 ::misin::misin ❓
 ::bişey::bişey 🤔
 ::hadi::hadi 🥱⏲
 ::şu::şu 👈
 ::istiyorum::istiyorum 👍
 ::gerçekten::gerçekten 
 ::artık::artık ⌚❌
 ::kim::kim 🤨
 ::bay::bay 🤵
 ::buraya::buraya 👇
 ::pekii::pekii 👍
 ::başka::başka 🤔
 ::gerçekten mi::gerçekten mi? 🤨
 ::aga::aga 🤨📿
 ::nargile::nargile 🤨📿
 ::belki::belki 🤔
 ::tanrım::tanrım 😇✝
 ::tek::tek 👆
 ::olur::olur 👍
 ::adam::adam 🤵
 ::sanırım::sanırım 🤔
 ::orada::orada 😮👉
 ::nerede::nerede 🤨
 ::biz::biz 👨‍👩‍👧‍👦
 ::hiçbir::hiçbir ❌
 ::yardım::yardım 🥺🙏
 ::bilmiyorum::bilmiyorum 🤷‍♂️
 ::gün::gün 🌞
 ::gece::gece 🌝
 ::fazla::fazla 😮
 ::hemen::hemen 🏃‍💨
 ::oh::oh 😌
 